version: '3'

services:
    app:
        build: .
        command: yarn start
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - .:/usr/app
        container_name: knowledge
